In [1]:
import pandas as pd

In [43]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [88]:
# Pandas comes with a few built-in conditional selectors, two of which we will highlight here.
# The first is isin. isin is lets you select data whose value "is in" a list of values. For example,
# heres how we can use it to select wines only from Italy or France:

# reviews.loc[reviews.country.isin(['Italy', 'France'])]
# df3.to_csv('PandasCovidProject.csv',index=False)

# Series

In [4]:
pd.Series([0.25,0.5,0.75,1.0])

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [12]:
data=pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [18]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [20]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [89]:
print(pd.__version__)

2.2.2

In [90]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [91]:
dic={'A':1,'B':2,'C':3,'D':4}
d=pd.Series(dic)
d

A    1
B    2
C    3
D    4
dtype: int64

In [141]:
d['A':'C']

A    1
B    2
C    3
dtype: int64

In [93]:
d[0:2]

A    1
B    2
dtype: int64

# DataFrame

In [44]:
grades = pd.Series({'A':4,'A-':3.5,'B':3,'B-':2.5,'B':2})
marks = pd.Series({'A':85,'A-':80,'B':75,'B-':70,'B':65})
df=pd.DataFrame({'Grades':grades,'Marks':marks})
df

    Grades  Marks
A      4.0     85
A-     3.5     80
B      2.0     65
B-     2.5     70

In [34]:
df.T

           A    A-     B    B-
Grades   4.0   3.5   2.0   2.5
Marks   85.0  80.0  65.0  70.0

In [110]:
df.values

array([[ 4. , 85. ],
       [ 3.5, 80. ],
       [ 2. , 65. ],
       [ 2.5, 70. ]])

In [36]:
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([6,7,8,9,0])
d=pd.DataFrame({'S1':s1,'S2':s2})
d

   S1  S2
0   1   6
1   2   7
2   3   8
3   4   9
4   5   0

In [112]:
df.values[0,1]

85.0

In [38]:
df.columns

Index(['Grades', 'Marks'], dtype='object')

In [46]:
df['ScaledMarks']=100*(df['Marks']/90) ## Or df['ScaledMarks']=100*(marks.values/90)
df

    Grades  Marks  ScaledMarks
A      4.0     85    94.444444
A-     3.5     80    88.888889
B      2.0     65    72.222222
B-     2.5     70    77.777778

In [127]:
del df['ScaledMarks']
df

    Grades  Marks
A      4.0     85
A-     3.5     80
B      2.0     65
B-     2.5     70

In [139]:
G= df[df['Marks']>=80]
G

    Grades  Marks
A      4.0     85
A-     3.5     80

# Get Or Find Null Values

In [60]:
D=pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])
D

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [62]:
import numpy as np
df = pd.DataFrame([[np.nan, 2, np.nan, 0],[3, 4, np.nan, 1],[np.nan, np.nan, np.nan, np.nan],[np.nan, 3, np.nan, 4]],columns=['A','B','C','D'])
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [66]:
D.fillna(0)  # fillna used to fill All Nan values

     a  b    c
0  1.0  2  0.0
1  0.0  3  4.0

In [68]:
D.dropna()   # dropna used Drop the rows where at least one element is missing.

Empty DataFrame
Columns: [a, b, c]
Index: []

In [78]:
D.dropna(axis=1)

   b
0  2
1  3

In [72]:
data=pd.Series([0.25,0.5,0.75,1.0],index=[1,3,5,9])  # index are explicit index
                                                     # default index i.e 0,1,2,3... are implicit index
data

1    0.25
3    0.50
5    0.75
9    1.00
dtype: float64

In [74]:
data[1:3]   # ans is gives using implicit index of this index array not use index

3    0.50
5    0.75
dtype: float64

In [229]:
# the problem solve by loc and iloc
data.loc[1:3]  # use explicil indexes

1    0.25
3    0.50
dtype: float64

In [231]:
data.iloc[1:3] # use implicit indexes

3    0.50
5    0.75
dtype: float64

In [82]:
grades = pd.Series({'A':4,'A-':3.5,'B':3,'B-':2.5,'B':2})
marks = pd.Series({'A':85,'A-':80,'B':75,'B-':70,'B':65})
df=pd.DataFrame({'Grades':grades,'Marks':marks})
df

    Grades  Marks
A      4.0     85
A-     3.5     80
B      2.0     65
B-     2.5     70

In [92]:
df.iloc[2,:]  # use implicit index means default index like array index

Grades     2.0
Marks     65.0
Name: B, dtype: float64

In [98]:
print(df.iloc[2,:]['Grades'])

2.0

## Revision

In [9]:
ser=pd.Series({3:1,2:2,5:3,1:4,4:5})
ser2=pd.Series({3:23,2:43,5:55,1:23,4:50})
df=pd.DataFrame({"A":ser,"B":ser2})
df

   A   B
3  1  23
2  2  43
5  3  55
1  4  23
4  5  50

In [3]:
import numpy as np
import pandas as pd

In [5]:
df=pd.DataFrame({"A":{3:1,2:2,5:3,1:4,4:5},"B":{3:23,2:43,5:55,1:23,4:50}})
df=pd.DataFrame([{3:np.nan,2:2,5:3,1:4,4:np.nan},{3:23,2:np.nan,5:55,1:np.nan,4:50}])
df

      3    2   5    1     4
0   NaN  2.0   3  4.0   NaN
1  23.0  NaN  55  NaN  50.0

In [7]:
df=df.dropna(axis=1)
df

    5
0   3
1  55

# Work on CSV

In [10]:
from sklearn.impute import SimpleImputer

In [3]:
df=pd.read_csv("country_wise_latest.csv")
df

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [105]:
df.rename_axis("Info",axis=1).rename_axis('Index',axis=0)

Info,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
Index,,,,,,,,,,,,,,,
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

## reviews["country"].value_counts() → Faster & simpler for counting values in a single column.
## reviews.groupby("country").size() → More flexible if you need additional operations later.

In [99]:
df[pd.isnull(df['Confirmed'])]

Empty DataFrame
Columns: [Country/Region, Confirmed, Deaths, Recovered, Active, New cases, New deaths, New recovered, Deaths / 100 Cases, Recovered / 100 Cases, Deaths / 100 Recovered, Confirmed last week, 1 week change, 1 week % increase, WHO Region]
Index: []

## dtype

In [93]:
df['Confirmed'].astype('float64')
# It's possible to convert a column of one type into another wherever such a conversion makes sense by using the astype() function.

0      36263.0
1       4880.0
2      27973.0
3        907.0
4        950.0
        ...
182    10621.0
183       10.0
184     1691.0
185     4552.0
186     2704.0
Name: Confirmed, Length: 187, dtype: float64

## Note: count() return datafarme and it required "by" function in sort
##       while size() return series and it not required "by" function in sort

## **Sorting**

In [89]:
df.sort_values(by=['Confirmed','Deaths'],ascending=False).reset_index()

,index,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,173,US,4290259,148011,1325804,2816444,56336,1076,27941,3.45,30.90,11.16,3834677,455582,11.88,Americas
1,23,Brazil,2442375,87618,1846641,508116,23284,614,33728,3.59,75.61,4.74,2118646,323729,15.28,Americas
2,79,India,1480073,33408,951166,495499,44457,637,33598,2.26,64.26,3.51,1155338,324735,28.11,South-East Asia
3,138,Russia,816680,13334,602249,201097,5607,85,3077,1.63,73.74,2.21,776212,40468,5.21,Europe
4,154,South Africa,452529,7067,274925,170537,7096,298,9848,1.56,60.75,2.57,373628,78901,21.12,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,49,Dominica,18,0,18,0,0,0,0,0.00,100.00,0.00,18,0,0.00,Americas
183,140,Saint Kitts and Nevis,17,0,15,2,0,0,0,0.00,88.24,0.00,17,0,0.00,Americas
184,68,Greenland,14,0,13,1,1,0,0,0.00,92.86,0.00,13,1,7.69,Europe
185,75,Holy See,12,0,12,0,0,0,0,0.00,100.00,0.00,12,0,0.00,Europe
186,183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa

In [87]:
df.sort_index()  # give original dataframe

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [73]:
df.groupby(['Country/Region'])["Confirmed"].agg([min,max,len])
## This code groups a DataFrame (df) by the column "Country/Region" and calculates three aggregate statistics (len, min, and max) 
## for the "Confirmed" column.

C:\Users\sky\AppData\Local\Temp\ipykernel_9776\1629920207.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby(['Country/Region'])["Confirmed"].agg([min,max,len])
C:\Users\sky\AppData\Local\Temp\ipykernel_9776\1629920207.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby(['Country/Region'])["Confirmed"].agg([min,max,len])

                      min    max  len
Country/Region
Afghanistan         36263  36263    1
Albania              4880   4880    1
Algeria             27973  27973    1
Andorra               907    907    1
Angola                950    950    1
...                   ...    ...  ...
West Bank and Gaza  10621  10621    1
Western Sahara         10     10    1
Yemen                1691   1691    1
Zambia               4552   4552    1
Zimbabwe             2704   2704    1

[187 rows x 3 columns]

In [11]:
df.groupby("WHO Region").apply(lambda d:d["Confirmed"].iloc[0] )## first inde in series

C:\Users\sky\AppData\Local\Temp\ipykernel_9776\3180610278.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("WHO Region").apply(lambda d:d["Confirmed"].iloc[0] )

WHO Region
Africa                    27973
Americas                     86
Eastern Mediterranean     36263
Europe                     4880
South-East Asia          226225
Western Pacific           15303
dtype: int64

In [12]:
df.head() # default gives 5 top records 
df.head(10) # gives 10 records

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
5,Antigua and Barbuda,86,3,65,18,4,0,5,3.49,75.58,4.62,76,10,13.16,Americas
6,Argentina,167416,3059,72575,91782,4890,120,2057,1.83,43.35,4.21,130774,36642,28.02,Americas
7,Armenia,37390,711,26665,10014,73,6,187,1.90,71.32,2.67,34981,2409,6.89,Europe
8,Australia,15303,167,9311,5825,368,6,137,1.09,60.84,1.79,12428,2875,23.13,Western Pacific
9,Austria,20558,713,18246,1599,86,1,37,3.47,88.75,3.91,19743,815,4.13,Europe

In [46]:
df['Country/Region']+ " - "+df['WHO Region']

0             Afghanistan - Eastern Mediterranean
1                                Albania - Europe
2                                Algeria - Africa
3                                Andorra - Europe
4                                 Angola - Africa
                          ...
182    West Bank and Gaza - Eastern Mediterranean
183                       Western Sahara - Africa
184                 Yemen - Eastern Mediterranean
185                               Zambia - Africa
186                             Zimbabwe - Africa
Length: 187, dtype: object

## There are two mapping methods that you will use often.
## map() is the first, and slightly simpler one. For example, suppose that we wanted to remean the scores the wines received to 0. We can do this as follows:

In [35]:
active_mean=df['active'].mean()
df['active'].map(lambda a:a-active_mean)

0     -24205.935829
1     -32010.935829
2     -26028.935829
3     -33949.935829
4     -33334.935829
           ...
182   -27210.935829
183   -34000.935829
184   -33626.935829
185   -32404.935829
186   -31875.935829
Name: Active, Length: 187, dtype: float64

## apply() is the equivalent method if we want to transform a whole DataFrame by calling a custom method on each row.

In [44]:
def reSetActive(row):
    row['Active']=row['Active']-active_mean
    return row
df.apply(reSetActive,axis='columns')   # this is return dataFrame

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,-24205.935829,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,-32010.935829,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,-26028.935829,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,-33949.935829,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,-33334.935829,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,West Bank and Gaza,10621,78,3752,-27210.935829,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,-34000.935829,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,-33626.935829,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,-32404.935829,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,-31875.935829,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [37]:
df.tail()

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [61]:
del df["1 week % increase"]
del df["Deaths / 100 Cases"]
df.drop(["Deaths / 100 Recovered","Recovered / 100 Cases"],axis=1,inplace=True)

In [63]:
df.head()

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Confirmed last week,1 week change,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,35526,737,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,4171,709,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,23691,4282,Africa
3,Andorra,907,52,803,52,10,0,0,884,23,Europe
4,Angola,950,41,242,667,18,1,0,749,201,Africa

In [65]:
df.isnull().sum()    # Count nan values from entire Data Frame

Country/Region         0
Confirmed              0
Deaths                 0
Recovered              0
Active                 0
New cases              0
New deaths             0
New recovered          0
Confirmed last week    0
1 week change          0
WHO Region             0
dtype: int64

In [67]:
df.head()

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Confirmed last week,1 week change,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,35526,737,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,4171,709,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,23691,4282,Africa
3,Andorra,907,52,803,52,10,0,0,884,23,Europe
4,Angola,950,41,242,667,18,1,0,749,201,Africa

In [69]:
df.rename(columns={"Deaths":"TapakGye"},inplace=True)
df.head()

,Country/Region,Confirmed,TapakGye,Recovered,Active,New cases,New deaths,New recovered,Confirmed last week,1 week change,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,35526,737,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,4171,709,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,23691,4282,Africa
3,Andorra,907,52,803,52,10,0,0,884,23,Europe
4,Angola,950,41,242,667,18,1,0,749,201,Africa

## Pandas Dates=> pd["Date"]=pd.to_datatime(df["Date"])

In [72]:
df.describe()

,Confirmed,TapakGye,Recovered,Active,New cases,New deaths,New recovered,Confirmed last week,1 week change
count,1.870000e+02,187.000000,1.870000e+02,1.870000e+02,187.000000,187.000000,187.000000,1.870000e+02,187.000000
mean,8.813094e+04,3497.518717,5.063148e+04,3.400194e+04,1222.957219,28.957219,933.812834,7.868248e+04,9448.459893
std,3.833187e+05,14100.002482,1.901882e+05,2.133262e+05,5710.374790,120.037173,4197.719635,3.382737e+05,47491.127684
min,1.000000e+01,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+01,-47.000000
25%,1.114000e+03,18.500000,6.265000e+02,1.415000e+02,4.000000,0.000000,0.000000,1.051500e+03,49.000000
50%,5.059000e+03,108.000000,2.815000e+03,1.600000e+03,49.000000,1.000000,22.000000,5.020000e+03,432.000000
75%,4.046050e+04,734.000000,2.260600e+04,9.149000e+03,419.500000,6.000000,221.000000,3.708050e+04,3172.000000
max,4.290259e+06,148011.000000,1.846641e+06,2.816444e+06,56336.000000,1076.000000,33728.000000,3.834677e+06,455582.000000

In [74]:
df.describe()["Confirmed"]

count    1.870000e+02
mean     8.813094e+04
std      3.833187e+05
min      1.000000e+01
25%      1.114000e+03
50%      5.059000e+03
75%      4.046050e+04
max      4.290259e+06
Name: Confirmed, dtype: float64

In [48]:
df['Active'].median()

1600.0

In [76]:
row_count = df.shape[0]
col_count = df.shape[1]
print(f"Row Count {row_count} ,Col Count {col_count}")

Row Count 187 ,Col Count 11

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Country/Region       187 non-null    object
 1   Confirmed            187 non-null    int64
 2   TapakGye             187 non-null    int64
 3   Recovered            187 non-null    int64
 4   Active               187 non-null    int64
 5   New cases            187 non-null    int64
 6   New deaths           187 non-null    int64
 7   New recovered        187 non-null    int64
 8   Confirmed last week  187 non-null    int64
 9   1 week change        187 non-null    int64
 10  WHO Region           187 non-null    object
dtypes: int64(9), object(2)
memory usage: 16.2+ KB

In [80]:
    df2=df.groupby('Country/Region')[['Confirmed','TapakGye','Recovered']].sum().reset_index()
df2
## To get count of ['Confirmed','TapakGye','Recovered'] for each country with respect to any DateTime , NewCase colouns etc.
## Than use this upper command( Note : In this csv there is no repectation of country that why df ka rows==)

         Country/Region  Confirmed  TapakGye  Recovered
0           Afghanistan      36263      1269      25198
1               Albania       4880       144       2745
2               Algeria      27973      1163      18837
3               Andorra        907        52        803
4                Angola        950        41        242
..                  ...        ...       ...        ...
182  West Bank and Gaza      10621        78       3752
183      Western Sahara         10         1          8
184               Yemen       1691       483        833
185              Zambia       4552       140       2815
186            Zimbabwe       2704        36        542

[187 rows x 4 columns]

In [82]:
df2=df.groupby('WHO Region')[['Confirmed','TapakGye','Recovered']].sum().reset_index()
df2
## To get count of ['Confirmed','TapakGye','Recovered'] for each WHORegion with respect to any country , NewCase colouns etc.
## Than use this upper command

              WHO Region  Confirmed  TapakGye  Recovered
0                 Africa     723207     12223     440645
1               Americas    8839286    342732    4468616
2  Eastern Mediterranean    1490744     38339    1201400
3                 Europe    3299523    211144    1993723
4        South-East Asia    1835297     41349    1156933
5        Western Pacific     292428      8249     206770

In [86]:
df3=df.groupby(['WHO Region','Country/Region'])[['Confirmed','TapakGye','Recovered']].sum().reset_index()
df3.to_csv('PandasCovidProject.csv',index=False)

In [291]:
df3=df[df['Confirmed']>1000]
df3

,Country/Region,Confirmed,TapakGye,Recovered,Active,New cases,New deaths,New recovered,Confirmed last week,1 week change,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,35526,737,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,4171,709,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,23691,4282,Africa
6,Argentina,167416,3059,72575,91782,4890,120,2057,130774,36642,Americas
7,Armenia,37390,711,26665,10014,73,6,187,34981,2409,Europe
...,...,...,...,...,...,...,...,...,...,...,...
180,Venezuela,15988,146,9959,5883,525,4,213,12334,3654,Americas
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,8916,1705,Eastern Mediterranean
184,Yemen,1691,483,833,375,10,4,36,1619,72,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3326,1226,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1713,991,Africa